version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APIGET_AVAY: "https://api.example.com"
        VITE_ALLOWED_HOST: "example.com"
    ports:
      - "3000:3000"
    restart: unless-stopped
